name: Cross-Platform Cross-Compiler Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++-14]
        
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake for macos-latest
      if: runner.os == 'macOS'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations"
    
    - name: Configure CMake 
      if: runner.os != 'macOS'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
# Testing is disabled temporarily.
  # - name: Test
  #  working-directory: ${{github.workspace}}/build
  # run: ctest -C ${{env.BUILD_TYPE}}

